import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"
opacity = 0.85
option_as_alt = "Both"

[font]
normal = { family = "HackGen Console NF", style = "Regular" }
size = 14

